/**
 * Fahrzeugdaten für den Geraetefinder
 * @module data
 */

/**
 * Array mit allen Fahrzeugen und deren Ausrüstung
 * @type {Array<Object>}
 */
export const vehicles = [
	{
		name: "TLF",
		plate: "WL-R 5810",
		equipment: [
			{
				room: "G1",
				image: "src/img/tlf_g1.jpg",
				items: [
					{ quantity: 2, name: "Wathosen" },
					{ quantity: 2, name: "Unterlegkeile" },
					{ quantity: 1, name: "Bodengestellt für Werfer" },
					{ quantity: 1, name: "Bügelsäge" },
					{ quantity: 1, name: "Motorsäge mit Zubehör" },
					{ quantity: 2, name: "Schutzausrüstung für Motorsäge" },
					{ quantity: 2, name: "hydraulische Winden 10t" },
					{ quantity: 1, name: "Tauchpumpe" },
					{ quantity: 2, name: "Leitungstrommeln 230V" },
					{ quantity: 1, name: "Mulde" },
					{ quantity: 1, name: "Werkzeugkasten" },
				],
			},
			{
				room: "G2",
				image: "src/img/tlf_g2.jpg",
				items: [
					{ quantity: null, name: "Druckschläuche D mit Zubehör" },
					{ quantity: 1, name: "Kellersaugkorb" },
					{ quantity: 1, name: "Wasserstrahlpumpe" },
					{ quantity: 4, name: "Druckschläuche C" },
					{ quantity: 6, name: "Druckschläuche B" },
					{ quantity: 4, name: "Schlauchtragekörbe C" },
					{ quantity: 4, name: "Sack Ölbindemittel" },
				],
			},
			{
				room: "G3",
				image: "src/img/tlf_g3.jpg",
				items: [
					{ quantity: 1, name: "Kübelspritze" },
					{ quantity: 2, name: "Feuerlöscher PG12" },
					{ quantity: 1, name: "Handspritze für Ölbindemittel" },
					{ quantity: 1, name: "Kanister flüssiges Ölbindemittel" },
					{ quantity: 1, name: "Eimer Streusalz" },
					{ quantity: 1, name: "Hilfe Rucksack" },
				],
			},
			{
				room: "G4",
				image: "src/img/tlf_g4.jpg",
				items: [
					{ quantity: 9, name: "Verkehrsleitkegel" },
					{ quantity: 8, name: "Euroblitzer" },
					{ quantity: 2, name: "Handscheinwerfer" },
					{ quantity: 1, name: "Hygienebrett" },
				],
			},
			{
				room: "G5",
				image: "src/img/tlf_g5.jpg",
				items: [
					{ quantity: null, name: "Druckschläuche D mit Zubehör" },
					{ quantity: 1, name: "Kellersaugkorb" },
					{ quantity: 1, name: "Wasserstrahlpumpe" },
					{ quantity: 4, name: "Druckschläuche C" },
					{ quantity: 6, name: "Druckschläuche B" },
					{ quantity: 4, name: "Schlauchtragekörbe C" },
					{ quantity: 4, name: "Sack Ölbindemittel" },
				],
			},
			{
				room: "G6",
				image: "src/img/tlf_g6.jpg",
				items: [
					{ quantity: null, name: "Druckschlauch S 25" },
					{ quantity: null, name: "Hohlstrahlrohre C" },
					{ quantity: null, name: "Strahlrohre C" },
					{ quantity: null, name: "Strahlrohr B" },
					{ quantity: 2, name: "Übergangsstücke B-C" },
					{ quantity: 1, name: "Übergangsstück C" },
					{ quantity: 4, name: "Seilschlauchhalter" },
					{ quantity: 1, name: "Stützkrümmer" },
					{ quantity: 1, name: "Kombischaumrohr M4/S4" },
					{ quantity: 1, name: "Löschlanze" },
					{ quantity: 1, name: "Paar Schachthaken" },
					{ quantity: 1, name: "Standrohr" },
					{ quantity: 1, name: "Hydroschild B" },
					{ quantity: 1, name: "Druckbegrenzungsventil" },
					{ quantity: 2, name: "Absperrhähne B" },
					{ quantity: 1, name: "Krümmer 90°" },
					{ quantity: 2, name: "Verteiler" },
					{ quantity: null, name: "div. Kupplungsschlüssel" },
					{ quantity: 1, name: "Druckschlauch B" },
				],
			},
			{
				room: "GR",
				image: "src/img/tlf_gr.jpg",
				items: [
					{ quantity: 1, name: "5m Druckschlauch B" },
					{ quantity: 1, name: "Sammelstück" },
					{ quantity: 1, name: "Saugkorb" },
					{ quantity: 1, name: "Saugschutzkorb" },
					{ quantity: 2, name: "Mehrzweckleinen" },
					{ quantity: 3, name: "Kupplungsschlüssel" },
					{ quantity: 1, name: "2m Handsprechfunkgerät" },
					{ quantity: 1, name: "Übergangsstück A-B" },
					{ quantity: 3000, name: "Liter Wassertank" },
					{ quantity: 150, name: "Liter Schaummitteltank" },
					{ quantity: null, name: "Pumpe" },
				],
			},
			{
				room: "Dach",
				image: "src/img/tlf_gd.jpg",
				items: [
					{ quantity: 1, name: "Steckleiter" },
					{ quantity: 4, name: "Schlauchbrücken" },
					{ quantity: 1, name: "Einreißhaken" },
					{ quantity: 6, name: "Saugschläuche A" },
					{ quantity: 2, name: "Schaufeln" },
					{ quantity: 1, name: "Besen" },
					{ quantity: 1, name: "Spaten" },
					{ quantity: 4, name: "Feuerpatschen" },
					{ quantity: 1, name: "Wasserwerfer" },
					{ quantity: 1, name: "Abgasschlauch" },
				],
			},
			{
				room: "MR",
				image: "src/img/tlf_gm.jpg",
				items: [
					{ quantity: 2, name: "Preßluftatmer" },
					{ quantity: null, name: "Zubehör für Atemschutz" },
					{ quantity: 1, name: "Atemschutznotfalltasche" },
					{ quantity: 2, name: "2m Funkgeräte" },
					{ quantity: 9, name: "Warnwesten" },
					{ quantity: 2, name: "Handscheinwerfer" },
					{ quantity: 2, name: "Anhaltestäbe" },
					{ quantity: 2, name: "Decken" },
					{ quantity: 1, name: "Bolzenschneider" },
					{ quantity: null, name: "Ersatz Einsatzkleidung" },
					{ quantity: null, name: "div. Fahrzeugzubehör" },
					{ quantity: 1, name: "Wärmebildkamera" },
				],
			},
		],
	},

	{
		name: "LF",
		plate: "WL-R 5820",
		equipment: [
			{
				room: "G1",
				image: "src/img/lf_g1.jpg",
				items: [
					{ quantity: 1, name: "Trennschleifer mit Zubehoer" },
					{ quantity: 4, name: "Verkehrsleitkegel" },
					{ quantity: 2, name: "Wathosen" },
					{ quantity: 1, name: "Auffangmulde VA" },
					{ quantity: 1, name: "Stromerzeuger 5 kVA mit Zubehoer" },
					{ quantity: 2, name: "Flutlichtstrahler + Zubehoer" },
					{ quantity: 4, name: "Blitzleuchten" },
					{ quantity: 1, name: "Leistungstrommel" },
					{ quantity: 1, name: "Werkzeugkasten" },
					{ quantity: null, name: "Diverse Ruesthoelze" },
				],
			},
			{
				room: "G2",
				image: "src/img/lf_g2.jpg",
				items: [
					{ quantity: 4, name: "Ersatz Einsatzkleidung" },
					{ quantity: 1, name: "Erste Hilfe Koffer" },
					{ quantity: 2, name: "Feuerwehräxte" },
					{ quantity: 1, name: "Standrohr 2B" },
					{ quantity: 1, name: "Unterflurhydrantenschlüssel" },
					{ quantity: 1, name: "Überflurhydrantenschlüssel" },
					{ quantity: 2, name: "Brechstangen 700" },
					{ quantity: 1, name: "Bügelsäge" },
					{ quantity: 1, name: "Brechschneideisen" },
					{ quantity: 1, name: "Spaten" },
					{ quantity: 2, name: "Pressluftatmer + Zubehör" },
					{ quantity: 1, name: "Rettungsbrett" },
					{ quantity: 1, name: "Hydroaggregat Schere + Spreizer" },
				],
			},
			{
				room: "G3",
				image: "src/img/lf_g3.jpg",
				items: [
					{ quantity: 13, name: "Druckschläuche B20" },
					{ quantity: 7, name: "Druckschläuche C" },
					{ quantity: 4, name: "Schutzanzüge" },
					{ quantity: null, name: "Körperschutzform 2 / Schuhüberzieher" },
					{ quantity: 2, name: "Unterlegkeile" },
					{ quantity: null, name: "Diverse Rüsthölzer" },
				],
			},
			{
				room: "G4",
				image: "src/img/lf_g4.jpg",
				items: [
					{ quantity: 1, name: "Druckschlauch S25" },
					{ quantity: 5, name: "Druckschläuche C" },
					{ quantity: 1, name: "Strahlrohr B" },
					{ quantity: 4, name: "Strahlrohre C" },
					{ quantity: 1, name: "Stützkrümmer" },
					{ quantity: 2, name: "Übergangsstücke B-C" },
					{ quantity: 2, name: "Schaummittelbehälter" },
					{ quantity: 1, name: "Mittelschaumpistole" },
					{ quantity: 1, name: "Feuerlöscher PG6" },
					{ quantity: 1, name: "Feuerlöscher CO<sub>2</sub>" },
					{ quantity: 1, name: "Kübelspritze" },
					{ quantity: 1, name: "Verbandkasten K" },
					{ quantity: 1, name: "Verteiler B-CBC mit Druckschlauch B20" },
				],
			},
			{
				room: "GR",
				image: "src/img/lf_gr.jpg",
				items: [
					{ quantity: 800, name: "Liter Wassertank" },
					{ quantity: 1, name: "Saugkorb A" },
					{ quantity: 1, name: "Saugkorbschutz A" },
					{ quantity: 1, name: "Sammelstück A-B2" },
					{ quantity: 4, name: "Saugschläuche A" },
					{ quantity: 5, name: "Mehrzweckleinen" },
					{ quantity: 3, name: "Kupplungsschlüssel" },
					{ quantity: 2, name: "Schachthaken" },
					{ quantity: 1, name: "Verteiler B-CBC" },
					{ quantity: null, name: "Pumpe" },
				],
			},
			{
				room: "Dach",
				image: "src/img/lf_gd.jpg",
				items: [
					{ quantity: 2, name: "Schlauchbrücken" },
					{ quantity: 1, name: "Steckleiter 4-teilig" },
					{ quantity: 1, name: "Einreißhaken 2,5" },
					{ quantity: 2, name: "Feuerpatchen" },
					{ quantity: 1, name: "Dunghacke" },
					{ quantity: 2, name: "Besen" },
					{ quantity: 1, name: "Sack Ölbindemittel" },
					{ quantity: 1, name: "Eimer Chemikalienbindemittel" },
					{ quantity: 1, name: "Saugschlauch A" },
					{ quantity: 6, name: "Chemikalienschutzanzug" },
					{ quantity: 6, name: "Sprechgarnituren" },
					{ quantity: null, name: "Zubehör CSA Anzüge" },
				],
			},
			{
				room: "MR",
				image: "src/img/lf_gm.jpg",
				items: [
					{ quantity: 2, name: "Handsprechfunkgeräte 2m" },
					{ quantity: 1, name: "ExWarn-Meßgerät" },
					{ quantity: 2, name: "Preßluftatmer + Zubehör" },
					{ quantity: 9, name: "Warnwesten" },
					{ quantity: 3, name: "Handscheinwerfer" },
					{ quantity: 8, name: "Feuerwehrleinen" },
					{ quantity: 8, name: "Breitgurte" },
					{ quantity: 1, name: "Hommel" },
					{ quantity: 1, name: "Krankentrage" },
					{ quantity: 2, name: "Decken" },
				],
			},
			{
				room: "Fahrer",
				image: "src/img/lf_gf.jpg",
				items: [
					{ quantity: 2, name: "Anhaltestäbe" },
					{ quantity: 1, name: "Handscheinwerfer" },
					{ quantity: 1, name: "Funkgerät 4m" },
					{ quantity: 2, name: "Funkgeräte 2m" },
					{ quantity: 1, name: "Funkmappe" },
					{ quantity: 1, name: "Handy" },
					{ quantity: 1, name: "Stoffteddy" },
				],
			},
		],
	},
	{
		name: "RW",
		plate: "WL-LK 810",
		equipment: [
			{
				room: "G1",
				image: "src/img/rw_g1.jpg",
				items: [
					{ quantity: 2, name: "Wathosen" },
					{ quantity: 1, name: "Motorkettensäge inkl. Zubehör" },
					{ quantity: 1, name: "Motortrennschleifer inkl. Zubehör" },
					{ quantity: 3, name: "Leitungstrommeln 230 V davon 1 Ex geschützt" },
					{ quantity: 2, name: "Leitungstrommeln 400 V davon 1 Ex geschützt" },
					{ quantity: 1, name: "E – Verteiler" },
					{ quantity: null, name: "Erdungskabel und Erdungsspieß" },
					{ quantity: null, name: "Dichtungspropfen und Keile" },
				],
			},
			{
				room: "G2",
				image: "src/img/rw_g2.jpg",
				items: [
					{ quantity: 2, name: "Besen" },
					{ quantity: 2, name: "Schaufeln" },
					{ quantity: 2, name: "Wasserschieber" },
					{ quantity: 2, name: "Hebekissen 40t inkl. Zubehör" },
					{ quantity: null, name: "Spanngurte" },
					{ quantity: null, name: "Rüsthölzer" },
					{ quantity: 1, name: "Erdanker inkl. Zubehör" },
					{ quantity: 2, name: "Hydraulische Winde 10t" },
					{ quantity: 5, name: "Stahlseile in verschiedener Länge" },
					{ quantity: null, name: "Hebesatz 15t" },
					{ quantity: null, name: "Mehrzweckzug Z16" },
					{ quantity: null, name: "Kantenreiter" },
					{ quantity: null, name: "Armatur-Druckplatten" },
					{ quantity: null, name: "Umlenkrolle 22t" },
				],
			},
			{
				room: "G3 (v)",
				image: "src/img/rw_g3_v.jpg",
				items: [
					{ quantity: null, name: "Kübelspritze" },
					{ quantity: null, name: "Feuerlöscher" },
					{ quantity: null, name: "Bergetuch" },
					{ quantity: null, name: "Wagenheber" },
					{ quantity: null, name: "Stromerzeuger 12 KVA" },
				],
			},
			{
				room: "G3 (h)",
				image: "src/img/rw_g3_h.jpg",
				items: [
					{ quantity: null, name: "Schutzbrillen" },
					{ quantity: null, name: "Gehörstöpsel" },
					{ quantity: null, name: "Staubmasken" },
					{ quantity: 2, name: "1000 Watt Strahler" },
					{ quantity: 1, name: "Stativ" },
					{ quantity: 2, name: "Gefahrgutfässer" },
					{ quantity: 1, name: "Vacuumfass" },
				],
			},
			{
				room: "G4 (v)",
				image: "src/img/rw_g4_v.jpg",
				items: [
					{ quantity: 1, name: "Glasmaster" },
					{ quantity: 3, name: "Rettungszylinder RZ 1 – 3" },
					{ quantity: 1, name: "Pedalschneider" },
					{ quantity: 1, name: "Schwelleraufsatz" },
					{ quantity: 1, name: "Tripple Hydraulikaggregat Weber" },
					{ quantity: 1, name: "Spreizer SP 60 Weber" },
					{ quantity: 1, name: "Rettungsschere RS 170-105 Weber" },
					{ quantity: 2, name: "Brechstangen" },
				],
			},
			{
				room: "G4 (h)",
				image: "src/img/rw_g4_h.jpg",
				items: [
					{ quantity: 3, name: "Pressluftflaschen" },
					{ quantity: 4, name: "Stab-Pack" },
					{ quantity: 1, name: "Rangierkupplung" },
					{ quantity: null, name: "div. Schäkel und Anschlagketten" },
					{ quantity: null, name: "Spreizerzubehör" },
					{ quantity: 1, name: "Bügelsäge" },
					{ quantity: 1, name: "Bolzenschneider" },
					{ quantity: 2, name: "Äxte" },
					{ quantity: 1, name: "Vorschlaghammer" },
					{ quantity: 1, name: "Kuhfuss" },
					{ quantity: 2, name: "Klappspaten" },
				],
			},
			{
				room: "G5",
				image: "src/img/rw_g5.jpg",
				items: [
					{ quantity: null, name: "div. Schutzhandschuhe" },
					{ quantity: null, name: "Schachthaken" },
					{ quantity: 8, name: "Mehrzweckleinen" },
					{ quantity: null, name: "PVC Einhängebehälter" },
					{ quantity: null, name: "Fließlappen" },
					{ quantity: 2, name: "Auffangbehälter" },
					{ quantity: null, name: "Gefahrgutschläuche Metall" },
				],
			},
			{
				room: "G6",
				image: "src/img/rw_g6.jpg",
				items: [
					{ quantity: 4, name: "Euroblitzer" },
					{ quantity: null, name: "Absperrband und Stützen" },
					{ quantity: null, name: "Schilderständer und Warnschilder" },
					{ quantity: 1, name: "Set Turbo – Flaire" },
					{ quantity: 6, name: "Verkehrsleitkegel" },
					{ quantity: 3, name: "Handscheinwerfer" },
					{ quantity: null, name: "Bedienteil Stromgenerator" },
					{ quantity: null, name: "Bedienteil Fahrzeugtechnik HMI" },
				],
			},
			{
				room: "G7",
				image: "src/img/rw_g7.jpg",
				items: [
					{ quantity: 2, name: "C-Druckschläuche säurefest" },
					{ quantity: 1, name: "Ausgußrohr" },
					{ quantity: 1, name: "Handmembranpumpe" },
					{ quantity: null, name: "Rohrwinkel" },
					{ quantity: 1, name: "Saugkorb für Gefahrgut" },
					{ quantity: null, name: "Übergangsstücke" },
					{ quantity: null, name: "Einschaltstrombegrenzer" },
					{ quantity: null, name: "Werkzeug nicht funkenreißend" },
					{ quantity: null, name: "Dichtungsmaterial" },
					{ quantity: 1, name: "Elro Gefahrgutpumpe" },
					{ quantity: 1, name: "Druckbelüfter" },
					{ quantity: 4, name: "Unterlegkeile" },
					{ quantity: 2, name: "20L Dieselkanister" },
				],
			},
			{
				room: "G8",
				image: "src/img/rw_g8.jpg",
				items: [
					{ quantity: null, name: "TBD" },
				],
			},
			{
				room: "GR",
				image: "src/img/rw_gr.jpg",
				items: [
					{ quantity: 4, name: "Unisafe Öl u. Chemikalienbinder" },
					{ quantity: 1, name: "Rettungsrucksack" },
					{ quantity: 4, name: "Stifneck Halskrausen" },
					{ quantity: 1, name: "Beatmungsgerät" },
					{ quantity: 1, name: "Defibrilator" },
					{ quantity: 1, name: "Verbandkasten für Verbrennungen" },
					{ quantity: 1, name: "Werkzeugkoffer Feuerwehr" },
					{ quantity: 1, name: "Werkzeugkoffer Elektro" },
					{ quantity: 1, name: "Absturzsicherung" },
					{ quantity: 2, name: "Decken" },
					{ quantity: 4, name: "Leichensäcke" },
					{ quantity: null, name: "div. Laken und Tücher" },
					{ quantity: null, name: "div. Nägel und Schrauben" },
					{ quantity: 4, name: "Sack Ölbindmittel" },
				],
			},
			{
				room: "Dach",
				image: "src/img/rw_gd.jpg",
				items: [
					{ quantity: 1, name: "Krankentrage" },
					{ quantity: 1, name: "Rettungsbrett" },
					{ quantity: 1, name: "4 teilige Steckleiter" },
					{ quantity: 1, name: "LKW Rettungsplattform" },
					{ quantity: 2, name: "Auffangmulden" },
					{ quantity: 1, name: "Fasspumpe" },
					{ quantity: null, name: "Ansaugrohr für Gefahrgut" },
					{ quantity: null, name: "Saugdruckschläuche säurefest" },
				],
			},
		],
	},
];
